// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GTFit - Transforme seu corpo e mente com IA",
  description: "O aplicativo fitness mais completo do Brasil. Contador de calorias com IA, planos de treino personalizados com vídeos 3D, acompanhamento nutricional profissional e transformação corporal realista. Mais de 50.000 brasileiros já transformaram suas vidas.",
  keywords: "fitness, treino, nutrição, dieta, calorias, IA, inteligência artificial, academia, musculação, emagrecimento, hipertrofia, saúde, bem-estar",
  authors: [{ name: "GTFit" }],
  openGraph: {
    title: "GTFit - Transforme seu corpo e mente com IA",
    description: "O aplicativo fitness mais completo do Brasil. Contador de calorias com IA, treinos personalizados e muito mais.",
    url: "https://gtfit.com.br",
    siteName: "GTFit",
    locale: "pt_BR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "GTFit - Transforme seu corpo e mente com IA",
    description: "O aplicativo fitness mais completo do Brasil. Contador de calorias com IA, treinos personalizados e muito mais.",
  },
  robots: {
    index: true,
    follow: true,
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
